package com.brinta.tutumridez.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity representing address details including street and city.
 * This class is mapped to a database table by JPA.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Address {

    /**
     * Primary key of the Address entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue( strategy = GenerationType.IDENTITY )
    private Long id;
    
    /**
     * Street portion of the address.
     * Example: "123 Main St".
     */
    private String street;
    
    /**
     * City name corresponding to the address.
     * Example: "New York".
     */
    private String city;
}
