package com.brinta.tutumridez.entity.bank;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Data
@Table( name = "Users", catalog = "Employee_Systems" )
public class User {
	
    /**
     * Primary key of the Address entity.
     * Auto-generated by the database.
     */
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
    
    /**
     * Street portion of the address.
     * Example: "123 Main St".
     */
	@Column(name = "user_name")
	private String name;
	
    

	

}
